### ISSUE TITLE
Select Inventory List shows disclosure indicators for all lists

### ISSUE THREAD

**Issue by vatthikorn** [Grocee/grocee-ui#29]
In Select Inventory List screen, each cell has the chevron on the non-default lists as shown below. They shouldn't have them.

![simulator screen shot - iphone x - 2018-09-16 at 00 03 30](https://user-images.githubusercontent.com/5591523/45592760-1ec5e300-b944-11e8-99c6-2683047d419c.png)

**Comment by indirap** [comment]
Should be fixed in #28
